[package]
name = "logosq_benchmark"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "logosq_benchmark"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
num-complex = "0.4"
criterion = { version = "0.5", features = ["html_reports"] }
rayon = "1.7"
nalgebra = "0.32"
logosq = "0.1.12"
tqdm = "0.8.0"
